{{- range .Values.deploymentNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yatai
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yatai
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.yataiServiceAccount.name }}
    namespace: {{ $.Values.yataiServiceAccount.namespace }}
{{- end }}
