{{- if .Values.bentoDeploymentAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "yatai-deployment.serviceAccountNameWithBentoDeployment" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yatai-deployment.serviceAccountNameWithBentoDeployment" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-deployment.serviceAccountName" $ }}
    namespace: {{ $.Values.yataiSystem.namespace }}
{{ else }}

{{- range .Values.bentoDeploymentNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-deployment.serviceAccountNameWithBentoDeployment" $ }}
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-deployment.serviceAccountNameWithBentoDeployment" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-deployment.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}

{{- end }}
