apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-deployment.shared-envname" . }}
  namespace: {{ .Values.yataiSystem.namespace }}
  labels:
    {{- include "yatai-deployment.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_DEPLOYMENT_NAMESPACE: {{ .Release.Namespace }}
  {{- if .Values.bentoDeploymentNamespaces }}
  BENTO_DEPLOYMENT_NAMESPACES: {{ join "," .Values.bentoDeploymentNamespaces | quote }}
  {{- end }}
  BENTO_DEPLOYMENT_ALL_NAMESPACES: {{ .Values.bentoDeploymentAllNamespaces | quote }}
